/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'brand-yellow': '#FFE500',
        'on-surface': '#1e1c10',
        'on-surface-variant': '#4b4731',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#faf3df',
        'surface-container': '#f4eeda',
        'surface-container-high': '#eee8d4',
        'surface-container-highest': '#e9e2cf',
        'surface-variant': '#e9e2cf',
        'surface': '#ffffff',
        'background': '#ffffff',
        'tertiary-container': '#00fcfb',
        'tertiary-fixed': '#00fcfb',
        'on-tertiary-container': '#007171',
        'on-tertiary': '#ffffff',
        'secondary-container': '#e2e2e2',
        'secondary-fixed': '#e2e2e2',
        'on-secondary-container': '#646464',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'outline-variant': '#cec7aa',
      },
      fontFamily: {
        sans: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        display: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        body: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        none: '0px',
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '9999px',
      },
      boxShadow: {
        brutal: '4px 4px 0px 0px #1e1c10',
        'brutal-sm': '2px 2px 0px 0px #1e1c10',
        'brutal-hover': '2px 2px 0px 0px #1e1c10',
        layout: '4px 0px 0px 0px #1e1c10',
      },
      spacing: {
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '40px',
        xl: '64px',
      },
    },
  },
  plugins: [],
}
