const Investment = require('../models/investment.model');
const Insurance = require('../models/insurance.model');
const EMILoan = require('../models/loan.model');
const { investedValue } = require('../utils/investmentCalc');
const { TAX_CONFIG, DEFAULT_FY } = require('./taxConfig');

const FREQ_MONTHS = { Monthly: 1, Quarterly: 3, 'Half-Yearly': 6, Yearly: 12 };
const round = (n) => Math.round(n);

// ---------------------------------------------------------------------------
// All FY 2025-26 tax constants are imported from taxConfig.js.
// No tax number is hardcoded in this file.
// ---------------------------------------------------------------------------
const _cfg = TAX_CONFIG[DEFAULT_FY];

// Convenience aliases (retained for external callers that import these directly).
const STANDARD_DEDUCTION = _cfg.STANDARD_DEDUCTION;
const REBATE             = _cfg.REBATE;
const SLAB_BOUNDS        = _cfg.SLAB_BOUNDS;
const SLAB_RATES         = _cfg.SLAB_RATES;
const SURCHARGE_TIERS    = _cfg.SURCHARGE_TIERS;

function fmtINR(n) {
  if (!isFinite(n)) return '';
  return Math.round(n).toLocaleString('en-IN');
}

function buildSlabLabels(bounds) {
  const labels = [];
  let prev = 0;
  for (let i = 0; i < bounds.length; i++) {
    const upper = bounds[i];
    if (upper === Infinity) {
      labels.push(`Above ₹${fmtINR(prev)}`);
    } else if (prev === 0) {
      labels.push(`Up to ₹${fmtINR(upper)}`);
    } else {
      labels.push(`₹${fmtINR(prev + 1)} – ₹${fmtINR(upper)}`);
    }
    prev = upper;
  }
  return labels;
}
const SLAB_LABELS = {
  Old: buildSlabLabels(SLAB_BOUNDS.Old),
  New: buildSlabLabels(SLAB_BOUNDS.New),
};

// Return the surcharge bracket (lower bound + rate) the income falls into.
function surchargeBracket(totalIncome, regime) {
  let lower = 0;
  for (const t of _cfg.SURCHARGE_TIERS) {
    if (t.limit === Infinity) {
      return { lower, rate: regime === 'New' ? _cfg.NEW_SURCHARGE_CAP : _cfg.OLD_SURCHARGE_TOP };
    }
    if (totalIncome <= t.limit) return { lower, rate: t.rate };
    lower = t.limit;
  }
  return { lower, rate: 0 };
}

/**
 * Slab-wise tax on a given taxable income. Returns each band with the income
 * falling inside it, the rate, and the tax generated by that band, plus the
 * summed income tax (before rebate/surcharge).
 */
function computeSlabTax(taxable, regime) {
  const bounds = SLAB_BOUNDS[regime];
  const rates = SLAB_RATES[regime];
  const labels = SLAB_LABELS[regime];
  const t = Math.max(0, taxable);
  let prev = 0;
  let incomeTax = 0;
  const slabs = [];
  for (let i = 0; i < bounds.length; i++) {
    const upper = bounds[i];
    const rate = rates[i];
    const incomeInBand = Math.max(0, Math.min(t, upper) - prev);
    const tax = Math.round(incomeInBand * rate);
    slabs.push({
      label: labels[i],
      lower: prev === 0 ? 0 : prev + 1,
      upper: upper === Infinity ? null : upper,
      rate,
      incomeInBand,
      tax,
    });
    incomeTax += tax;
    prev = upper;
    if (t <= upper) break;
  }
  return { slabs, incomeTax };
}

/** Section 87A rebate with marginal relief (FY 2025-26). */
function computeRebate(taxable, regime, incomeTaxBeforeRebate) {
  const { threshold, max } = REBATE[regime];
  const eligibleRebate = Math.min(incomeTaxBeforeRebate, max);
  if (taxable <= threshold) return eligibleRebate;
  // Marginal relief: rebate is reduced by the amount income exceeds the
  // threshold, so the taxpayer does not lose the whole rebate for a small
  // excess. Tax payable then ≈ only the excess over the threshold.
  const reduced = eligibleRebate - (taxable - threshold);
  return Math.max(0, reduced);
}

/** Surcharge on income tax (after rebate) with marginal relief. */
function computeSurcharge(totalIncome, incomeTaxAfterRebate, regime) {
  const { lower: threshold, rate } = surchargeBracket(totalIncome, regime);
  if (rate === 0) return 0;
  const surcharge = Math.round(incomeTaxAfterRebate * rate);

  // Marginal relief: crossing a surcharge tier must not make the total tax
  // (income tax + surcharge) jump beyond the tax on the threshold income PLUS
  // the excess income above that threshold. The threshold is a gross income,
  // so we subtract the standard deduction before computing its slab tax.
  const thresholdTaxable = Math.max(0, threshold - _cfg.STANDARD_DEDUCTION[regime]);
  const taxAtThreshold = computeSlabTax(thresholdTaxable, regime).incomeTax;
  const maxPreCess = taxAtThreshold + (totalIncome - threshold);
  const currentPreCess = incomeTaxAfterRebate + surcharge;
  if (currentPreCess > maxPreCess) {
    return Math.max(0, Math.round(maxPreCess - incomeTaxAfterRebate));
  }
  return surcharge;
}

// Statutory HRA exemption (Old regime only). The exemption is the LEAST of:
//   (a) actual HRA received,
//   (b) 10% of basic salary,
//   (c) rent paid minus 10% of basic salary.
// If we lack the basic salary or the rent paid, we CANNOT compute it, so it
// returns 0 — we never guess an HRA exemption (the Form 16 may not state rent
// paid, which is exactly the "not enough information" case from the audit).
function computeHraExemption({ basicSalary = 0, hra = 0, rentPaid = null, regime }) {
  if (regime !== 'Old' || !basicSalary || rentPaid == null) return 0
  const tenPctBasic = 0.1 * basicSalary
  const rentLessTenPct = Math.max(0, rentPaid - tenPctBasic)
  return Math.max(0, Math.min(hra || 0, tenPctBasic, rentLessTenPct))
}

// Metadata for each deduction section: regime eligibility + statutory cap.
// `max` null means no statutory cap. Notes are static (not AI-generated).
const DED_META = {
  standardDeduction: {
    label: 'Standard Deduction',
    allowed: { Old: true, New: true },
    max: 'sd', // resolved per regime
    note: 'A flat deduction from salary income (Old ₹50,000 / New ₹75,000 for FY 2025-26).',
  },
  hra: {
    label: 'House Rent Allowance (HRA) Exemption',
    allowed: { Old: true, New: false },
    max: null,
    note: 'Least of actual HRA, 10% of basic salary, or rent paid minus 10% of basic. Allowed only under the Old regime.',
  },
  lta: {
    label: 'Leave Travel Allowance (LTA) Exemption',
    allowed: { Old: true, New: false },
    max: null,
    note: 'Exemption for actual travel on leave (twice in a block of 4 years). Allowed only under the Old regime.',
  },
  section80C: {
    label: 'Section 80C',
    allowed: { Old: true, New: false },
    max: _cfg.DEDUCTION_CAPS.SECTION_80C_GROUP,
    note: 'ELSS, PPF, life-insurance premiums, home-loan principal, children’s tuition fees. Capped at ₹1,50,000.',
  },
  section80CCD1B: {
    label: 'Section 80CCD(1B) — NPS',
    allowed: { Old: true, New: false },
    max: _cfg.DEDUCTION_CAPS.SECTION_80CCD1B,
    note: 'Additional deduction for your own NPS contribution, up to ₹50,000 (over and above 80C).',
  },
  section80CCD2: {
    label: 'Section 80CCD(2) — Employer NPS',
    allowed: { Old: true, New: true },
    max: null,
    note: 'Employer’s NPS contribution. Allowed under both regimes (treated as the NPS amount we hold).',
  },
  section80D: {
    label: 'Section 80D — Health Insurance',
    allowed: { Old: true, New: false },
    max: _cfg.DEDUCTION_CAPS.SECTION_80D_SELF,
    note: 'Health-insurance premium for self/family. Up to ₹25,000 (₹50,000 for senior citizens).',
  },
  section80E: {
    label: 'Section 80E — Education Loan Interest',
    allowed: { Old: true, New: false },
    max: null,
    note: 'Interest on an education loan for higher studies. No upper limit.',
  },
  section80G: {
    label: 'Section 80G — Donations',
    allowed: { Old: true, New: false },
    max: null,
    note: 'Eligible donations (50% or 100% deduction depending on the fund).',
  },
  section24: {
    label: 'Section 24(b) — Home Loan Interest',
    allowed: { Old: true, New: false },
    max: _cfg.DEDUCTION_CAPS.SECTION_24B,
    note: 'Interest paid on a home loan. Deduct up to ₹2,00,000 (self-occupied).',
  },
};

/**
 * Build the per-regime deduction plan. Each item shows whether the deduction is
 * allowed under the regime, the statutory cap, the amount the user actually
 * has (userAmount), the amount claimed, and the remaining eligible headroom.
 * Disallowed items are kept (claimed 0) so the UI can explain what is excluded.
 */
function buildDeductionPlan(regime, input, sources = {}) {
  const sd = STANDARD_DEDUCTION[regime];
  const plan = [];

  const push = (key, userAmount, source) => {
    const meta = DED_META[key];
    const allowed = meta.allowed[regime];
    const max = meta.max === 'sd' ? sd : meta.max;
    const cap = allowed ? (max == null ? Infinity : max) : 0;
    const claimed = allowed ? Math.min(userAmount, cap) : 0;
    const remaining = allowed && max != null ? Math.max(0, max - claimed) : allowed && max == null ? null : 0;
    plan.push({
      key,
      label: meta.label,
      allowed,
      disallowed: !allowed,
      maxLimit: max == null ? null : max,
      userAmount: round(userAmount),
      claimed: round(claimed),
      remaining, // null = unlimited, 0 = none, number = headroom
      qualifying: allowed && userAmount > 0,
      // Provenance: where this claimed amount came from (Form 16, the user's
      // declared records, or both). Null when nothing was claimed.
      source: source ?? (allowed && userAmount > 0 ? 'Declared' : null),
      note: meta.note,
    });
  };

  push('standardDeduction', sd, sources.standardDeduction);
  push('hra', input.hra || 0, sources.hra);
  push('lta', input.lta || 0, sources.lta);
  push('section80C', input.section80C || 0, sources.section80C);
  push('section80CCD1B', input.section80CCD || 0, sources.section80CCD1B);
  push('section80CCD2', input.section80CCD || 0, sources.section80CCD2);
  push('section80D', input.section80D || 0, sources.section80D);
  push('section80E', input.section80E || 0, sources.section80E);
  push('section80G', input.section80G || 0, sources.section80G);
  push('section24', input.section24 || 0, sources.section24);

  return plan;
}

/**
 * Full FY 2025-26 tax liability for one regime, following the statutory
 * waterfall. Returns every intermediate value so the UI can render (and expand)
 * each step.
 */
function computeLiability({
  grossSalary,
  regime,
  hra = 0,
  lta = 0,
  deductions = {},
  tdsDeducted = 0,
  advanceTax = 0,
  selfAssessmentTax = 0,
  sources = {},
}) {
  const sd = STANDARD_DEDUCTION[regime];

  // Salary exemptions are allowed only under the Old regime.
  const salaryExemptions = {
    hra: regime === 'Old' ? Math.max(0, hra || 0) : 0,
    lta: regime === 'Old' ? Math.max(0, lta || 0) : 0,
  };

  const incomeFromSalary = Math.max(0, (grossSalary || 0) - salaryExemptions.hra - salaryExemptions.lta);
  const incomeFromOtherSources = 0; // not captured in the app's data model
  const grossTotalIncome = Math.max(0, incomeFromSalary + incomeFromOtherSources);

  const plan = buildDeductionPlan(
    regime,
    {
      hra: salaryExemptions.hra,
      lta: salaryExemptions.lta,
      section80C: deductions.section80C || 0,
      section80CCD: deductions.section80CCD || 0,
      section80D: deductions.section80D || 0,
      section80E: deductions.section80E || 0,
      section80G: deductions.section80G || 0,
      section24: deductions.section24 || 0,
    },
    sources,
  );

  const totalDeductions = plan.reduce((s, d) => s + d.claimed, 0);
  const taxableIncome = Math.max(0, grossTotalIncome - totalDeductions);

  const slab = computeSlabTax(taxableIncome, regime);
  const incomeTaxBeforeRebate = slab.incomeTax;
  const rebate = computeRebate(taxableIncome, regime, incomeTaxBeforeRebate);
  const incomeTaxAfterRebate = Math.max(0, incomeTaxBeforeRebate - rebate);
  const surcharge = computeSurcharge(grossTotalIncome, incomeTaxAfterRebate, regime);
  const cess = Math.round((incomeTaxAfterRebate + surcharge) * _cfg.CESS);
  const finalTax = incomeTaxAfterRebate + surcharge + cess;

  const totalPaid = (tdsDeducted || 0) + (advanceTax || 0) + (selfAssessmentTax || 0);
  const balance = finalTax - totalPaid;
  const refund = balance < 0 ? Math.round(-balance) : 0;
  const taxPayable = balance > 0 ? Math.round(balance) : 0;

  return {
    regime,
    grossIncome: grossSalary || 0,
    salaryExemptions,
    incomeFromSalary,
    incomeFromOtherSources,
    grossTotalIncome,
    deductions: plan,
    totalDeductions,
    taxableIncome,
    slabs: slab.slabs,
    incomeTaxBeforeRebate,
    rebate,
    incomeTaxAfterRebate,
    surcharge,
    cess,
    finalTax,
    tdsDeducted: tdsDeducted || 0,
    advanceTax: advanceTax || 0,
    selfAssessmentTax: selfAssessmentTax || 0,
    totalPaid,
    refund,
    taxPayable,
  };
}

/**
 * Compute BOTH regimes from the SAME gross salary + SAME aggregated deductions,
 * so the recommendation compares like-for-like final tax liabilities.
 */
function computeRegimeTaxes(grossSalary, agg, extra = {}, sources = {}) {
  const base = {
    section80C: agg.section80C || 0,
    section80CCD: agg.section80CCD || 0,
    section80D: agg.section80D || 0,
    section80E: agg.section80E || 0,
    section80G: agg.section80G || 0,
    section24: agg.section24 || 0,
  };
  const old = computeLiability({ grossSalary, regime: 'Old', hra: extra.hra, lta: extra.lta, deductions: base, tdsDeducted: extra.tdsDeducted || 0, sources });
  const newR = computeLiability({ grossSalary, regime: 'New', hra: extra.hra, lta: extra.lta, deductions: base, tdsDeducted: extra.tdsDeducted || 0, sources });
  return { old, new: newR };
}

// Backwards-compatible thin wrapper used by a few legacy call sites.
function calculateTax(grossIncome, deductions, regime) {
  const r = computeLiability({
    grossSalary: grossIncome,
    regime,
    deductions: { section80C: deductions },
  });
  return {
    taxableIncome: r.taxableIncome,
    taxBeforeCess: r.incomeTaxAfterRebate,
    cess: r.cess,
    totalTax: r.finalTax,
  };
}

function annualize(amount, frequency) {
  if (!amount) return 0;
  if (frequency === 'One-time') return amount;
  const div = FREQ_MONTHS[frequency] || 12;
  return amount * (12 / div);
}

/**
 * Aggregate deductible amounts from all financial modules for a user.
 * Values are estimates suitable for a quick comparison/recommendation.
 */
async function aggregateDeductions(userId) {
  const [investments, insurances, loans] = await Promise.all([
    Investment.find({ memberId: userId }),
    Insurance.find({ memberId: userId }),
    EMILoan.find({ memberId: userId }),
  ]);

  let section80C = 0;
  let section80CCD = 0;
  let section80D = 0;
  let section80E = 0;
  let section80G = 0;
  let section24 = 0;

  for (const inv of investments) {
    if (inv.fundCategory === 'ELSS' || inv.assetType === 'PPF') section80C += investedValue(inv);
    if (inv.assetType === 'NPS') section80CCD += investedValue(inv);
  }

  for (const ins of insurances) {
    if (ins.insuranceType === 'Health') {
      section80D += annualize(ins.premiumAmount, ins.premiumFrequency);
    }
  }

  for (const loan of loans) {
    if (loan.loanType === 'Home' && loan.interestRate && loan.principalAmount) {
      const annualInterest = Math.min((loan.interestRate / 100) * loan.principalAmount, 200000);
      section24 += annualInterest;
      const principalRepaid = Math.max(0, (loan.emiAmount || 0) * 12 - annualInterest);
      section80C += principalRepaid;
    }
  }

  // Section 80C has a hard cap — read from config.
  section80C = Math.min(section80C, _cfg.DEDUCTION_CAPS.SECTION_80C_GROUP);

  const totalDeductions =
    section80C + section80CCD + section80D + section80E + section80G + section24;

  return {
    section80C: round(section80C),
    section80CCD: round(section80CCD),
    section80D: round(section80D),
    section80E: round(section80E),
    section80G: round(section80G),
    section24: round(section24),
    totalDeductions: round(totalDeductions),
  };
}

// Plain-English descriptions of each deduction section. Static reference text
// (never generated by AI) shown to the user so they understand what is claimed.
const DEDUCTION_INFO = {
  section80C: {
    label: 'Section 80C',
    note: 'Investments like ELSS, PPF and life-insurance premiums, the principal repaid on a home loan, and children’s tuition fees. Capped at ₹1,50,000 per year.',
  },
  section80CCD: {
    label: 'Section 80CCD(1B)',
    note: 'Extra deduction of up to ₹50,000 for NPS (pension) contributions, on top of the 80C limit.',
  },
  section80D: {
    label: 'Section 80D',
    note: `Health-insurance premium for you and your family. Up to ₹${_cfg.DEDUCTION_CAPS.SECTION_80D_SELF.toLocaleString('en-IN')} (₹${_cfg.DEDUCTION_CAPS.SECTION_80D_PARENTS.toLocaleString('en-IN')} for senior citizens).`,
  },
  section80E: {
    label: 'Section 80E',
    note: 'Interest on an education loan for higher studies. There is NO upper limit on this deduction.',
  },
  section24: {
    label: 'Section 24(b)',
    note: 'Interest paid on a home loan. You can deduct up to ₹2,00,000 per year.',
  },
};

// Build the static, plain-English breakdown of what was claimed (no AI).
function buildDeductionBreakdown(agg) {
  const mentionedSections = new Set();
  const breakdown = [];
  
  for (const section of Object.keys(DEDUCTION_INFO)) {
    const amount = round(agg[section] || 0);
    if (amount > 0 && !mentionedSections.has(section)) {
      mentionedSections.add(section);
      breakdown.push({
        section,
        label: DEDUCTION_INFO[section].label,
        amount,
        note: DEDUCTION_INFO[section].note,
      });
    }
  }
  
  return breakdown;
}

function inr(n) {
  return '₹' + Math.round(n).toLocaleString('en-IN');
}

/** Generate human-readable tax-saving tips based on current deductions. */
async function generateTips(userId) {
  const d = await aggregateDeductions(userId);
  const tips = [];

  const unused80C = Math.max(0, _cfg.DEDUCTION_CAPS.SECTION_80C_GROUP - d.section80C);
  if (unused80C > 0) {
    const saving = round(unused80C * 0.3);
    tips.push(
      `You have ${inr(unused80C)} of unused Section 80C limit. Invest in ELSS/PPF to save up to ${inr(saving)} in tax.`,
    );
  }

  const unused80D = Math.max(0, _cfg.DEDUCTION_CAPS.SECTION_80D_SELF - d.section80D);
  if (unused80D > 0) {
    tips.push(`You can claim up to ${inr(unused80D)} more under Section 80D (health insurance).`);
  }

  if (d.section80E === 0) {
    tips.push('No education loan interest claimed under 80E — if you have one, the interest is fully deductible.');
  }

  if (d.section24 === 0) {
    tips.push('No home loan interest claimed under Section 24 — if applicable, you can deduct up to ₹2,00,000.');
  }

  if (d.section80CCD === 0) {
    tips.push('Consider NPS (Section 80CCD(1B)) for an additional ₹50,000 deduction.');
  }

  if (tips.length === 0) {
    tips.push('You are utilising your major deductions well. Consider NPS for additional savings.');
  }

  return tips;
}

module.exports = {
  calculateTax,
  aggregateDeductions,
  generateTips,
  annualize,
  computeLiability,
  computeRegimeTaxes,
  computeSlabTax,
  computeRebate,
  computeSurcharge,
  computeHraExemption,
  buildDeductionPlan,
  buildDeductionBreakdown,
  STANDARD_DEDUCTION,
  REBATE,
};
