import type { Form16Regime, RegimeTrace, SlabRow, TaxpayerContext } from '../types'

// FY 2025-26 slabs — MUST mirror backend server/services/tax.service.js exactly.
const SLABS: Record<Form16Regime, [number, number][]> = {
  Old: [
    [250000, 0],
    [250000, 0.05],
    [500000, 0.2],
    [Infinity, 0.3],
  ],
  New: [
    [400000, 0],
    [400000, 0.05],
    [400000, 0.1],
    [400000, 0.15],
    [400000, 0.2],
    [400000, 0.25],
    [Infinity, 0.3],
  ],
}

const SLAB_LABELS: Record<Form16Regime, string[]> = {
  Old: [
    'Up to ₹2,50,000',
    '₹2,50,001 – ₹5,00,000',
    '₹5,00,001 – ₹10,00,000',
    'Above ₹10,00,000',
  ],
  New: [
    'Up to ₹4,00,000',
    '₹4,00,001 – ₹8,00,000',
    '₹8,00,001 – ₹12,00,000',
    '₹12,00,001 – ₹16,00,000',
    '₹16,00,001 – ₹20,00,000',
    '₹20,00,001 – ₹24,00,000',
    'Above ₹24,00,000',
  ],
}

// Simplified slab calc (FY 2025-26) — income tax before cess + 4% cess.
export function computeTax(taxable: number, regime: Form16Regime) {
  let remaining = Math.max(0, taxable)
  let before = 0
  for (const [span, rate] of SLABS[regime]) {
    if (remaining <= 0) break
    const portion = Math.min(remaining, span)
    before += portion * rate
    remaining -= span
  }
  const total = before + before * 0.04
  return { before: Math.round(before), total: Math.round(total) }
}

// Full slab rows (band label, rate, income in band, tax generated) — used by the
// fallback trace when a saved recommendation predates the rich regimes trace.
export function computeSlabRows(taxable: number, regime: Form16Regime): SlabRow[] {
  let remaining = Math.max(0, taxable)
  let lower = 0
  return SLABS[regime].map(([span, rate], i) => {
    const portion = Math.min(remaining, span)
    const tax = Math.round(portion * rate)
    const upper = span === Infinity ? Infinity : lower + span
    const row: SlabRow = {
      label: SLAB_LABELS[regime][i] ?? `Slab ${i + 1}`,
      lower,
      upper,
      rate,
      incomeInBand: Math.round(portion),
      tax,
    }
    lower = upper === Infinity ? lower : upper
    remaining -= span
    return row
  })
}

// Fallback builder — produces a minimal RegimeTrace from snapshot figures when the
// saved recommendation has no full `regimes` trace (generated by an older build).
// The TaxRecommendation page's main path uses the backend `regimes` trace.
export function buildRegimeTrace(
  regime: Form16Regime,
  gross: number,
  deductions: number,
  taxable: number,
): RegimeTrace {
  const { before, total } = computeTax(taxable, regime)
  const cess = total - before
  return {
    regime,
    grossIncome: gross,
    salaryExemptions: { hra: 0, lta: 0 },
    incomeFromSalary: gross,
    incomeFromOtherSources: 0,
    grossTotalIncome: gross,
    deductions: [],
    totalDeductions: deductions,
    taxableIncome: taxable,
    slabs: computeSlabRows(taxable, regime),
    incomeTaxBeforeRebate: before,
    rebate: 0,
    incomeTaxAfterRebate: before,
    surcharge: 0,
    cess,
    finalTax: total,
    tdsDeducted: 0,
    advanceTax: 0,
    selfAssessmentTax: 0,
    totalPaid: 0,
    refund: 0,
    taxPayable: total,
  }
}

// -----------------------------------------------------------------------------
// Live Review-page preview (Part 6). Mirrors the backend computeRegimeResult
// for the Form 16-only subset so the SAME numbers appear on every screen.
// The authoritative figures always come from the saved backend recommendation.
// -----------------------------------------------------------------------------
export const TAX_CONFIG = {
  '2025-26': {
    STANDARD_DEDUCTION: {
      Old: 50000,
      New: 75000,
    }
  }
}

const SD_PREVIEW: Record<Form16Regime, number> = TAX_CONFIG['2025-26'].STANDARD_DEDUCTION
const CAPS_PREVIEW: Record<string, number | null> = {
  '80C': 150000,
  '80CCD1B': 50000,
  '80D': 25000,
  '24b': 200000,
}
const VI_A_PREVIEW = new Set(['80C', '80CCD', '80CCD1B', '80CCD2', '80D', '80E', '80G', '24b'])

export interface TaxPreview {
  verifiedDeductions: number
  unverifiedDeductions: number
  duplicateFlaggedDeductions: number
  oldTaxable: number
  newTaxable: number
}

// Preview derived strictly from the canonical TaxpayerContext (no local re-sum).
// Returns three separate totals (Part 3):
//   verifiedDeductions     = needsConfirmation===false && source present && not duplicateRisk (capped)
//   unverifiedDeductions   = needsConfirmation===true (subsection unknown / confidence low)
//   duplicateFlaggedDeductions = duplicateRisk===true && needsConfirmation===false
//                              (amount applied at the capped value)
export function computeTaxPreview(ctx: TaxpayerContext): TaxPreview {
  const gross = ctx.salary.grossSalary || 0

  // Verified total uses Old regime (most permissive for VI-A deductions)
  const computeRegime = (regime: Form16Regime) => {
    let hra = 0
    let lta = 0
    for (const d of ctx.deductions) {
      if (d.section === 'HRA' && regime === 'Old') hra = d.amount || 0
      else if (d.section === 'LTA' && regime === 'Old') lta = d.amount || 0
    }
    const gti = Math.max(0, gross - hra - lta)
    let verified = 0
    let unverified = 0
    let duplicateFlagged = 0
    for (const d of ctx.deductions) {
      if (d.section === 'StandardDeduction' || d.section === 'HRA' || d.section === 'LTA') continue
      // Unverified: needsConfirmation===true (subsection unknown etc.)
      if (d.needsConfirmation) {
        unverified += d.amount || 0
        continue
      }
      // Duplicate-flagged: duplicateRisk===true but confirmed (secondary source)
      if (d.duplicateRisk) {
        duplicateFlagged += d.amount || 0
        continue
      }
      if (regime === 'New') {
        // New regime allows NONE of the Chapter VI-A deductions.
        if (VI_A_PREVIEW.has(d.section)) continue
      }
      if (!d.source) continue // no source = not applied
      const cap = CAPS_PREVIEW[d.section] ?? null
      const claimed = cap == null ? d.amount || 0 : Math.min(d.amount || 0, cap)
      verified += claimed
    }
    const totalDed = SD_PREVIEW[regime] + verified
    const taxable = Math.max(0, gti - totalDed)
    return { taxable, verified, unverified, duplicateFlagged }
  }

  const old = computeRegime('Old')
  const neu = computeRegime('New')
  return {
    verifiedDeductions: old.verified + SD_PREVIEW.Old,
    unverifiedDeductions: old.unverified, // Old regime view (most conservative)
    duplicateFlaggedDeductions: old.duplicateFlagged,
    oldTaxable: old.taxable,
    newTaxable: neu.taxable,
  }
}

// -----------------------------------------------------------------------------
// previewDeductionSplit — pure function that mirrors the three-condition
// inclusion filter in computeRegimeResult exactly (Part 3):
//   1. needsConfirmation === false
//   2. !!source
//   3. !duplicateRisk
// Returns { appliedDeductions, excludedDeductions, verifiedTotal, unverifiedTotal }
// for use on the Review page so the user sees exactly what will be applied.
// -----------------------------------------------------------------------------

export type SplitDeduction = {
  section: string
  subtype: string | null
  amount: number
  source: string | null
  reason?: string
}

export type DeductionSplit = {
  appliedDeductions: SplitDeduction[]
  excludedDeductions: SplitDeduction[]
  verifiedTotal: number
  unverifiedTotal: number
}

const SECTION_LABELS: Record<string, string> = {
  '80C': '80C — Tax-saving investments',
  '80CCD': '80CCD — NPS contributions',
  '80CCD1B': '80CCD(1B) — Additional NPS',
  '80D': '80D — Health insurance',
  '80E': '80E — Education loan interest',
  '80G': '80G — Donations',
  '24b': '24(b) — Home loan interest',
  'HRA': 'HRA exemption',
  'LTA': 'LTA exemption',
  'StandardDeduction': 'Standard deduction',
}

export function previewDeductionSplit(
  deductions: import('../types').DeductionLineItem[],
): DeductionSplit {
  const applied: SplitDeduction[] = []
  const excluded: SplitDeduction[] = []

  for (const d of deductions) {
    if (d.section === 'StandardDeduction' || d.section === 'HRA' || d.section === 'LTA') continue

    const label = SECTION_LABELS[d.section] ?? d.section

    if (d.needsConfirmation) {
      excluded.push({
        section: label,
        subtype: d.subtype,
        amount: d.amount || 0,
        source: d.source,
        reason: 'UNCONFIRMED — subsection or amount could not be confirmed',
      })
      continue
    }
    if (!d.source) {
      excluded.push({
        section: label,
        subtype: d.subtype,
        amount: d.amount || 0,
        source: null,
        reason: 'NO_SOURCE — provenance unknown',
      })
      continue
    }
    if (d.duplicateRisk) {
      excluded.push({
        section: label,
        subtype: d.subtype,
        amount: d.amount || 0,
        source: d.source,
        reason: 'DUPLICATE_RISK — secondary source; primary source already applied',
      })
      continue
    }
    // Passes all three conditions — applied (capped at statutory limit).
    const cap = CAPS_PREVIEW[d.section] ?? null
    const claimed = cap == null ? d.amount || 0 : Math.min(d.amount || 0, cap)
    applied.push({
      section: label,
      subtype: d.subtype,
      amount: claimed,
      source: d.source,
    })
  }

  const verifiedTotal = applied.reduce((s, a) => s + a.amount, 0)
  const unverifiedTotal = excluded.reduce((s, e) => s + e.amount, 0)
  return { appliedDeductions: applied, excludedDeductions: excluded, verifiedTotal, unverifiedTotal }
}
